Bug: timer delay when app is in background
phipsp/timetrk pull request #10
Opened 2021-02-27 17:56 UTC by anjakDev

The timer delay that was caused by the inaccuracy of setInterval due to JavaScript's single-threadedness should be fixed now. 
I followed the advice by https://medium.com/@abhi9bakshi/why-javascript-timer-is-unreliable-and-how-can-you-fix-it-9ff5e6d34ee0 and https://www.sitepoint.com/build-javascript-countdown-timer-no-dependencies/ to use Date objects to count down with. 

Closes #8

2021-02-28 19:26 UTC, phipsp requested changes
Good stuff 💯

2021-02-28 19:26 UTC, phipsp commented on src/utils/PomodoroTimer.js
> +    end.setSeconds(end.getSeconds() + immutableseconds)
I don't know if we need `immutableseconds`. Perhaps this is sufficient:

```suggestion
    end.setSeconds(end.getSeconds() + seconds)
```

2021-03-01 14:22 UTC, anjakDev commented on src/utils/PomodoroTimer.js
> +    end.setSeconds(end.getSeconds() + immutableseconds)
done

2021-03-02 19:34 UTC, phipsp approved these changes
🚀

2021-03-02 19:35 UTC, merged